import { Link } from "react-router-dom";
import { GoogleLogin } from "@react-oauth/google";
import { useLogin } from "../../hooks/useLogin";
import styles from "./LoginPage.module.css";

const Icons = {
  ShieldCheck: () => <svg width="48" height="48" fill="none" stroke="#10b981" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>,
  ArrowLeft: () => <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
};

export default function LoginPage() {
  const {
    email, setEmail, password, setPassword, rememberMe, setRememberMe,
    requires2FA, setRequires2FA, twoFactorCode, setTwoFactorCode, isVerifying,
    handleSubmit, handleVerify2FA, handleGoogleSuccess, handleGithubClick
  } = useLogin();

  return (
    <div className={styles.page}>

      <div className={styles.greenGlow} />
      <div className={styles.blueGlow} />

      <div className={styles.card}>

        {!requires2FA ? (
          <>
            <h1 className={styles.title}>
              Welcome <span className={styles.accent}>Back</span>
            </h1>
            <p className={styles.subtitle}>Log in to manage your career</p>

            <form onSubmit={handleSubmit} className={styles.form}>
              <div>
                <label className={styles.label}>Email Address</label>
                <input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="name@example.com" className={styles.input}   />
              </div>

              <div>
                <label className={styles.label}>Password</label>
                <input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" className={styles.input}   />
              </div>

              <div className={styles.options}>
                <label className={styles.rememberLabel}>
                  <input type="checkbox" checked={rememberMe} onChange={() => setRememberMe(!rememberMe)} className={styles.checkbox} />
                  Remember me
                </label>
                <Link to="/forgot-password" className={styles.forgotLink}>Forgot Password?</Link>
              </div>

              <button type="submit" className={styles.loginButton} >
                Login to Account
              </button>
            </form>

            <div className={styles.divider}>
              <div className={styles.dividerLine} />
              <span className={styles.dividerText}>OR CONTINUE WITH</span>
              <div className={styles.dividerLine} />
            </div>

            <div className={styles.socialButtons}>
              <div className={styles.googleButton}>
                <GoogleLogin onSuccess={handleGoogleSuccess} onError={() => alert('Google login failed')} type="icon" theme="filled_black" shape="circle" size="large" />
              </div>

              <button
                type="button" onClick={handleGithubClick}
                className={styles.githubButton}
              >
                <svg fill="#fff" viewBox="0 0 24 24" width="22" height="22">
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                </svg>
              </button>
            </div>

            <p className={styles.registerPrompt}>
              Don't have an account? <Link to="/register" className={styles.registerLink}>Register here</Link>
            </p>
          </>
        ) : (
          <div className={styles.verification}>
            <button onClick={() => setRequires2FA(false)} className={styles.backButton}>
              <Icons.ArrowLeft /> Back to login
            </button>

            <div className={styles.shield}>
              <Icons.ShieldCheck />
            </div>

            <h2 className={styles.verificationTitle}>Two-Factor Auth</h2>
            <p className={styles.verificationDescription}>
              Enter the 6-digit security code generated by your Authenticator app.
            </p>

            <form onSubmit={handleVerify2FA}>
              <input
                type="text" placeholder="000000" maxLength={6}
                value={twoFactorCode}
                onChange={(e) => setTwoFactorCode(e.target.value.replace(/\D/g, ''))}
                className={styles.codeInput}
              />

              <button
                type="submit" disabled={isVerifying || twoFactorCode.length !== 6}
                className={styles.verifyButton}
              >
                {isVerifying ? "Verifying..." : "Confirm & Login"}
              </button>
            </form>
          </div>
        )}

      </div>
    </div>
  );
}
